### ISSUE TITLE
False negative on amputatorbot.com when Javascript is not available

### ISSUE THREAD

**Issue by clemty** [KilledMufasa/AmputatorBot#11]
When visiting amputatorbot.com with Firefox and Noscript enabled and trying to remove AMP from https://www.bloomberg.com/amp/news/articles/2021-01-16/cyberpunk-2077-what-caused-the-video-game-s-disastrous-rollout only "Error: That doesn't look like a valid AMP URL!" is displayed. Also the "Try with an example"-Button does not do anything. After enabling JS/whitelisting in Noscript it works.

**Comment by KilledMufasa** [comment]
Hey there! Thanks for opening an issue about this. I looked into it, and your observation is correct. The reason why this happens is because the form was built somewhat hacky (https://www.amputatorbot.com/static/main.js) to, for instance, parse the values in the URL for easy access to the options. The 'false negative' is caused because the form isn't filled in correctly when submitting (because the JS is crucial in doing so). 

In the Debugger tab in Firefox you can see exactly which JS is used.

I would suggest to add amputatorbot.com to your allow-list, like you already did. Adding or changing stuff for when JavaScript is disabled can be, or at least in my opinion, hardly justified. So I'm afraid I won't be able to change this behaviour any time soon, sorry! Just know that I do appreciate you reaching out!
