### ISSUE TITLE
Suggestion: Add a public REST API that amputates links

### ISSUE THREAD

**Issue by Sv443** [KilledMufasa/AmputatorBot#12]
I'd love to be able to use your amputation in my own projects, so it would be really cool if there was a REST API that takes a URL and amputates it.  
I know this is a lot to ask and I would offer my help but I don't know Python at all, so I'm just throwing this suggestion out here in case you or anyone else would like to implement it.  
  
#### Example:  
`GET` to `https://amputatorbot.com/api/?url=https%3A%2F%2Fgoogle.com%2Famp%2Fs%2Ffoo.com%2Fbar`  
  
would return something like:  
```json
{
	"error": false,
	"url": "https://foo.com/bar"
}
```

**Comment by KilledMufasa** [comment]
Hi there! Thank you for the wonderful suggestion! After having received more requests like yours, I've decided to just go ahead and make one! [You can find the entire announcement here](https://www.reddit.com/r/AmputatorBot/comments/qpqipw/amputatorbot_v4_a_brandnew_api_databasecaching/). Or jump directly into the docs: [API Documentation](https://documenter.getpostman.com/view/12422626/UVC3n93T) & [Postman](https://www.postman.com/amputatorbot). 

I'll just go ahead and paste the announcement post here too:

(...)
![afbeelding](https://user-images.githubusercontent.com/25548343/140838648-e5af076a-db89-4d81-b571-00622b60564f.png)
The most interesting data that gets returned (for this request) is - of course - the canonical:

```
"canonical": { 
    "domain": "electrek",
     "is_alt": false,
     "is_amp": false,
     "is_cached": null,
     "is_valid": true,
     "type": "REL",
     "url": "https://electrek.co/2018/06/19/tesla-model-3-assembly-line-inside-tent-elon-musk/",
     "url_similarity": 0.8900523560209425
 }
```

- I dig it.

I've decided to open up this API to the public for free and without authentication, because hell, why not? It makes it easier for you guys to work with and for me to maintain. Worst case scenario is that people DDoS the shit out of our API, and to those I say, .. pls- just don't lol (I do got some things in place to keep stuff from going bananas of course, we'll just have to see how it goes).

I would love to hear about the projects you make with the API, feel free to comment or post about it on r/AmputatorBot!

----
Thx again for your suggestion! Without your issue, I probably wouldn't have made this. Let me know if the API is to your liking! Cheers!

**Comment by Sv443** [comment]
Thank you very much!  
I was thinking of making a userscript that automatically amputates any URL it finds, I'll make sure to try the API out soon.
