### ISSUE TITLE
Bot does not recognize Google pages on sites besides google.com

### ISSUE THREAD

**Issue by ntoskrnl4** [KilledMufasa/AmputatorBot#6]
Hey, quick thing I noticed when I summoned the bot:

The bot will recognize when AMP links are hosted on `google.com and add a little note to the end of the message: https://www.reddit.com/r/worldnews/comments/extdrc/thailand_cures_coronavirus_with_antihiv_drug/fge6u3g/?context=3

However, it will not recognize Google websites on foreign-country domains, such as `google.co.uk`, which is what happened when I summoned it (comment is invisible in the subreddit but shows on the profile): https://www.reddit.com/r/nextfuckinglevel/comments/exqwpv/they_actually_did_it_a_1000_bed_hospital/fge9t18/?context=3

Anyways, thank you for your work on the bot!

**Comment by KilledMufasa** [comment]
Hey there!

Thanks for submitting this issue, I didn't notice nor did I think about that! A few days ago I launched v1.8 in which I've implemented a fix for this issue. It used to be:

``` 
 if "google.com" in string or "ampproject.net" in string or "ampproject.org" in string:
        return True
```

and I've [since changed it](https://github.com/KilledMufasa/AmputatorBot/commit/ffdd9db62c4556be53b93e1ddaf7e9b63b76ca33#diff-b6b543613ad73a31a06cf5854e2716fe) to:

```   
if "www.google." in string or "ampproject.net" in string or "ampproject.org" in string:
        return True
```

So basically, if it detects any `www.google.(...) `it will now add the little note

Massive thx for pointing this out!
