### ISSUE TITLE
False positive, AMP tried to amputate an already canonical link

### ISSUE THREAD

**Issue by nicholas-thorpe** [KilledMufasa/AmputatorBot#9]
This problem was found in this thread: https://www.reddit.com/r/hockey/comments/i36dqw/kuzy_scores_on_pp_to_tie_game_at_2/g09gkwn/?context=2

The original comment was quickly deleted for reasons I'm not clear on.

What appears to have happened is it found the string "amp" in a link (https://www.gfycat.com/**amp**lepaltrycardinal) and attempted to cut it down to a canonical link despite it already being so.

**Comment by KilledMufasa** [comment]
Hi there, thx for opening the issue. The first thing I do when I get notified of a false positive is delete the comment before it spreads any more confusion. Sorry about that.

Back to topic: A day or 2 ago, I released v3.0: https://www.reddit.com/r/AmputatorBot/comments/i1wruh/amputatorbot_v30_better_bot/, which introduced something I like to call AMP-canonicals. The idea was that a cached AMP url was worse than a page simply using the AMP framework, so if AmputatorBot was able to remove the cached parts, it would share it - because that's better than nothing. However, I didn't account for the effect it would have on false positives.

To reproduce: https://www.amputatorbot.com/?https://github.com/orgs/ampproject/people

To fix: make the creation of AMP canonicals only available for cached pages

I expect to have fixed this within a day or 2, I'll lrt you know when I have an update. Thx again!

**Comment by KilledMufasa** [comment]
Hi again, the change I described earlier has gone live. This prevents AMP-canonicals from being used when the original AMP URL isn't cached. See the changes here: https://github.com/KilledMufasa/AmputatorBot/commit/1097cd75cc824dedea6c63d24af306db6ebf38c0

As you can see here, this fixes the false positives:

- https://www.amputatorbot.com/?https://github.com/orgs/ampproject/people

- https://www.amputatorbot.com/?https://www.gfycat.com/amplepaltrycardinal

Thx again for your help, much appreciated!
